//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RecordsInfo
    {
        public Nullable<int> fee { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> recordId { get; set; }
        public int InfoId { get; set; }
    
        public virtual Tbl_Records Tbl_Records { get; set; }
    }
}
