//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Records()
        {
            this.Tbl_RecordsInfo = new HashSet<Tbl_RecordsInfo>();
        }
    
        public int recordId { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_RecordsInfo> Tbl_RecordsInfo { get; set; }
    }
}
